name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs sender.c dataAquisition.c -o sender 
      
    - name: run sender
      #run: ./testchecker
      run: ./sender
    
    - name: build test
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage testChecker.cpp dataAquisition.c -o testchecker
      
    - name: run test
      run: ./testchecker

    - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs receiver.cpp receiveBatteryParameters.cpp -o receiver 
      
    - name: run receiver
      run: ./receiver
    
    - name: build test
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage testReceiver.cpp receiveBatteryParameters.cpp -o testReceiver
      
    - name: run test
      run: ./testReceiver
      
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
